name: Build on changes (PIO)

on:
  push:
    branches: [ main ]
    paths: [ 'Cubean/default/**' ]
  pull_request:
    paths: [ 'Cubean/default/**' ]
  workflow_dispatch:

jobs:
  call-builder:
    uses: ./.github/workflows/_pio-build.yml
    with:
      working_dir: Cubean/default
      envs: '["s3","s3-mini"]'
      cache_key_path: Cubean/default/platformio.ini
      artifact_prefix: cubean
