name: Release on tag (PIO)

on:
  push:
    tags: ['v*']
  workflow_dispatch:

permissions:
  contents: write   # required for gh release

jobs:
  build:
    uses: ./.github/workflows/_pio-build.yml
    with:
      working_dir: Cubean/default
      envs: '["s3","s3-mini"]'
      cache_key_path: Cubean/default/platformio.ini
      artifact_prefix: cubean

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download all firmware artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: cubean-*
          merge-multiple: true
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
